name: Check Changelog

on:
  pull_request:
    types: [opened, reopened, edited, labeled, unlabeled, synchronize]

permissions:
  contents: read

jobs:
  check-changelog:
    runs-on: ubuntu-latest
    if: |
      !contains(github.event.pull_request.body, '[skip changelog]') &&
      !contains(github.event.pull_request.body, '[changelog skip]') &&
      !contains(github.event.pull_request.body, '[skip ci]') &&
      !contains(github.event.pull_request.labels.*.name, 'skip changelog') &&
      !contains(github.event.pull_request.labels.*.name, 'dependencies') &&
      !contains(github.event.pull_request.labels.*.name, 'automation')
    steps:
      - uses: actions/checkout@v3
      - name: Check that CHANGELOG is touched
        run: |
          git fetch origin ${{ github.base_ref }} --depth 1 && \
          git diff remotes/origin/${{ github.base_ref }} --name-only | grep CHANGELOG.md
