name: Update Inventory
on:
  workflow_dispatch:
  schedule:
    - cron: '00 4 * * 1-5'

jobs:
  update-nodejs-inventory:
    name: Update Node.js Engine Inventory
    runs-on: pub-hk-ubuntu-22.04-small
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install Rust Inventory Binaries
        run: cargo install heroku-nodejs-utils --bin diff_versions --bin list_versions --git https://github.com/heroku/buildpacks-nodejs
      - id: set-diff-msg
        name: Set Diff Message
        run: echo "::set-output name=msg::$(diff_versions node inventory/node.toml)"
      - name: Rebuild Inventory
        run: "list_versions node > inventory/node.toml"
      - name: Update Changelog
        run: echo "${{ steps.set-diff-msg.outputs.msg }}" | xargs -r -I '{}' perl -i -p -e 's/## main\s+/## main\n\n- {}/' CHANGELOG.md
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4.2.4
        with:
          title: "Update Node.js Engine Inventory"
          commit-message: "Update Inventory for heroku/nodejs engine\n\n${{ steps.set-diff-msg.outputs.msg }}"
          branch: update-nodejs-inventory
          labels: "automation"
          body: "Automated pull-request to update heroku/nodejs engine inventory:\n\n${{ steps.set-diff-msg.outputs.msg }}"
  update-yarn-inventory:
    name: Update Node.js Yarn Inventory
    runs-on: pub-hk-ubuntu-22.04-small
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - id: install-rust-toolchain
        name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install Rust Inventory Binaries
        run: cargo install heroku-nodejs-utils --bin diff_versions --bin list_versions --git https://github.com/heroku/buildpacks-nodejs
      - id: set-diff-msg
        name: Set Diff Message
        run: echo "::set-output name=msg::$(diff_versions yarn inventory/yarn.toml)"
      - name: Rebuild Inventory
        run: "list_versions yarn > inventory/yarn.toml"
      - name: Update Changelog
        run: echo "${{ steps.set-diff-msg.outputs.msg }}" | xargs -r -I '{}' perl -i -p -e 's/## main\s+/## main\n\n- {}/' CHANGELOG.md
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4.2.4
        with:
          title: "Update Node.js Yarn Inventory"
          commit-message: "Update Inventory for heroku/nodejs yarn\n\n${{ steps.set-diff-msg.outputs.msg }}"
          branch: update-yarn-inventory
          labels: "automation"
          body: "Automated pull-request to update heroku/nodejs yarn inventory:\n\n${{ steps.set-diff-msg.outputs.msg }}"
